name: "Add Build environment"
description: "Prepares the basic build environment for compiling mods. This is a shortcut for installing the .NET version used by the game (currently .NET 6) and creating a 'game folder' with reference assemblies."

inputs:
    dotnet_version:
        description: "The .NET SDK version to install. This should usually be left as-is. Default: `6.0.x`."
        required: false
        default: "6.0.x"

runs:
    using: "composite"
    steps:
        - name: Install .NET ${{inputs.dotnet_version}}
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: ${{inputs.dotnet_version}}

        - name: Add reference assemblies
          uses: Pathoschild/SMAPI-ModBuildWorkflow/add-reference-assemblies@v0
